### ISSUE TITLE
fix bug: assign user to task - only Bob possible to assign even though he is not in the team

### ISSUE THREAD

**Issue by ViAarisKea** [KEA-GruppeJVK/Eksamen#66]

**Comment by KristofferKay** [comment]
Bob is I think the only meme er who has employee role so he is the only one that's able to be assigned. Should we include the PM also? Don't think clients should be assigned

**Comment by KristofferKay** [comment]
Nevermind I can see what the issue is - will fix later today.

**Comment by KristofferKay** [comment]
Completed
